[manager]

linemode = "size_and_mtime"
show_hidden = true
show_symlinks = true
sort_by = "alphabetical"
sort_order = "ascending"
sort_case_insensitive = true
show_icons = true

[opener]
edit = [
    {run = 'nvim "$@"', block = true, for = "unix"}
]
